# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Josh Beveridge
email: me@joshbeveridge.com
description: > # this means to ignore newlines until "baseurl:"
    This archive includes thoughts on design, gaming and regular comic reviews.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joshbeveridge.com" # the base hostname & protocol for your site
twitter_username: joshdrink
github_username:  joshdrink

# Build settings
markdown: kramdown

exclude: [_posts/drafts, assets/post, assets/node_modules, assets/bower_components, assets/fonts/4.4.0, projects.html, _posts/2016-02-01-site-list.markdown, _posts/2016-03-26-dcu-rebirth.markdown]

permalink: /:categories/:year/:month/:title/

gems:
  - jekyll-sitemap
